# yaml 配置
version: "3.7"
services:
  redis507:
    image: "redis:5.0.7"
    ports:
      - "26379:6379"
  mysql8021:
    image: "mysql:8.0.21"
    restart: always
    ports:
      - "23306:3306"
    command: "--default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql"
    environment:
      MYSQL_ROOT_PASSWORD: "gree123"
    volumes:
      - ./init.sql:/data/application/init.sql
  bluebell_app:
    build: .
    command: sh -c "./wait-for.sh redis507:6379 mysql8021:3306 -- ./bluebell_app"
    depends_on:
      - mysql8021
      - redis507
    ports:
      - "9090:9090"